In [29]:
import pandasdmx as sdmx
import requests
import pandas as pd

In [2]:
ausbs = sdmx.Request('ABS_XML')

In [3]:
flow_msg = ausbs.dataflow()

2022-08-09 20:43:44,211 pandasdmx.reader.sdmxml - DEBUG: Truncate sub-microsecond time in <Prepared>

In [4]:
flow_msg.response.url

'https://api.data.abs.gov.au/dataflow/ABS/latest'

In [5]:
flow_msg

<pandasdmx.StructureMessage>
  <Header>
    id: 'IDREF78336'
    prepared: '2022-08-09T20:25:10.098528+10:00'
    receiver: <Agency Unknown>
    sender: <Agency Unknown>
    source:
    test: False
  response: <Response [200]>
  DataflowDefinition (773): ABORIGINAL_POP_PROJ ABORIGINAL_POP_PROJ_REM...
  DataStructureDefinition (773): ABORIGINAL_POP_PROJ ABORIGINAL_POP_PRO...

In [6]:
flow_msg.dataflow.RES_DWELL_ST

In [13]:
res_dwell_st_msg = ausbs.dataflow('RES_DWELL_ST')

2022-08-09 20:49:15,794 pandasdmx.reader.sdmxml - DEBUG: Truncate sub-microsecond time in <Prepared>

--- SS without DSD ---
{1: False}

--- <class 'pandasdmx.message.StructureMessage'> ---
{2: <pandasdmx.StructureMessage>
  <Header>
    id: 'IDREF78325'
    prepared: '2022-08-09T20:20:05.867806+10:00'
    receiver: <Agency Unknown>
    sender: <Agency Unknown>
    source:
    test: False}

--- <class 'pandasdmx.model.DataStructureDefinition'> ---
{'RES_DWELL_ST': <DataStructureDefinition ABS:RES_DWELL_ST(1.0.0): Residential Dwellings: Values, Mean Price and Number by State and Territories Datastructure>}

--- <class 'pandasdmx.model.Agency'> ---
{'ABS': <Agency ABS>}

--- <class 'pandasdmx.model.DataflowDefinition'> ---
{'RES_DWELL_ST': <DataflowDefinition ABS:RES_DWELL_ST(1.0.0): Residential Dwellings: Values, Mean Price and Number by State and Territories>}

--- <class 'pandasdmx.model.CategoryScheme'> ---
{68: <CategoryScheme ABS:INDUSTRY(1.0.0) (8 items): Industries>, 69: <CategoryScheme ABS:INDUSTRY(1.0.0) (1 items)>}

--- <class 'pandasdmx.model.Categorisation'> ---
{'CAT_RES_DWELL_ST': <Categorisation ABS:CAT_RES_DWELL_ST(1.0.0): RES_DWELL_ST  CAtegorisation>}

--- <class 'pandasdmx.model.Codelist'> ---
{'CL_FREQ': <Codelist ABS:CL_FREQ(1.0.0) (9 items): Frequency>, 'CL_OBS_STATUS': <Codelist ABS:CL_OBS_STATUS(1.0.0) (16 items): Observation Status>, 'CL_RES_DWELL_ST_MEASURE': <Codelist ABS:CL_RES_DWELL_ST_MEASURE(1.0.0) (5 items): Measure>, 'CL_STATE': <Codelist ABS:CL_STATE(1.0.0) (10 items): State>, 'CL_UNIT_MEASURE': <Codelist ABS:CL_UNIT_MEASURE(1.0.0) (88 items): Unit of Measure>, 'CL_UNIT_MULT': <Codelist ABS:CL_UNIT_MULT(1.0.0) (31 items): Unit Multiplier>}

--- <class 'pandasdmx.model.ConceptScheme'> ---
{801: <ConceptScheme ABS:CS_COMMON(1.0.0) (5 items): Common Concepts>, 802: <ConceptScheme ABS:CS_COMMON(1.0.0) (1 items)>, 808: <ConceptScheme ABS:CS_GEOGRAPHY(1.0.0) (25 items): Geography Concepts>, 809: <ConceptScheme ABS:CS_GEOGRAPHY(1.0.0) (1 items)>, 'CS_COMMON': <ConceptScheme ABS:CS_COMMON(1.0.0) (3 items)>, 826: <ConceptScheme ABS:CS_ATTRIBUTE(1.0.0) (6 items): Attribute Concepts>, 827: <ConceptScheme ABS:CS_ATTRIBUTE(1.0.0) (1 items)>, 'CS_ATTRIBUTE': <ConceptScheme ABS:CS_ATTRIBUTE(1.0.0) (3 items)>}

--- <class 'pandasdmx.model.Annotation'> ---
{'obs_count': Annotation(id='obs_count', title='1890', type='sdmx_metrics', url=None, text=), 856: Annotation(id=None, title='A', type='ReleaseVersion', url=None, text=)}

--- Name ---
{857: ('en', 'Availability (A) for RES_DWELL_ST')}

--- <class 'pandasdmx.reader.sdmxml.Reference'> ---
{'RES_DWELL_ST': <pandasdmx.reader.sdmxml.Reference object at 0x000001BF6FB60548>}

--- <class 'pandasdmx.model.MemberSelection'> ---
{864: <MemberSelection MEASURE in {'1', '2', '3', '4', '5'}>, 874: <MemberSelection REGION in {'1', '2', '3', '4', '5', '6', '7', '8', 'AUS'}>, 876: <MemberSelection FREQ in {'Q'}>}

--- <class 'pandasdmx.model.RangePeriod'> ---
{879: RangePeriod(start=Period(is_inclusive=True, period=datetime.datetime(2011, 7, 1, 0, 0)), end=Period(is_inclusive=True, period=datetime.datetime(2021, 12, 31, 0, 0)))}

<common:KeyValue xmlns:common="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common" xmlns:message="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message" xmlns:structure="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/structure" id="TIME_PERIOD">
            <common:TimeRange/></common:KeyValue>
        </structure:CubeRegion>
      </structure:ContentConstraint>
      <structure:ContentConstraint id="CR_B_RES_DWELL_ST" agencyID="ABS" version="1.0.0" validFrom="2022-06-14T12:00:00" isFinal="false" type="Actual">
        <common:Annotations>
          <common:Annotation id="obs_count">
            <common:AnnotationTitle>1935</common:AnnotationTitle>
            <common:AnnotationType>sdmx_metrics</common:AnnotationType>
          </common:Annotation>
          <common:Annotation>
            <common:AnnotationTitle>B</common:AnnotationTitle>
            <common:AnnotationType>ReleaseVersion</common:AnnotationType>
          </common:Annotation>
        </common:Annotations>
        <common:Name xml:lang="en">Availability (B) for RES_DWELL_ST</common:Name>
        <structure:ConstraintAttachment>
          <structure:Dataflow>
            <Ref id="RES_DWELL_ST" version="1.0.0" agencyID="ABS" package="datastructure" class="Dataflow"/>
          </structure:Dataflow>
        </structure:ConstraintAttachment>
        <structure:CubeRegion include="true">
          <common:KeyValue id="MEASURE">
            <common:Value>1</common:Value>
            <common:Value>2</common:Value>
            <common:Value>3</common:Value>
            <common:Value>4</common:Value>
            <common:Value>5</common:Value>
          </common:KeyValue>
          <common:KeyValue id="REGION">
            <common:Value>1</common:Value>
            <common:Value>2</common:Value>
            <common:Value>3</common:Value>
            <common:Value>4</common:Value>
            <common:Value>5</common:Value>
            <common:Value>6</common:Value>
            <common:Value>7</common:Value>
            <common:Value>8</common:Value>
            <common:Value>AUS</common:Value>
          </common:KeyValue>
          <common:KeyValue id="FREQ">
            <common:Value>Q</common:Value>
          </common:KeyValue>
          <common:KeyValue id="TIME_PERIOD">
            <common:TimeRange>
              <common:StartPeriod isInclusive="true">2011-07-01T00:00:00</common:StartPeriod>
              <common:EndPeriod isInclusive="true">2022-03-31T00:00:00</common:EndPeriod>
            </common:TimeRange>
          </common:KeyValue>
        </structure:CubeRegion>
      </structure:ContentConstraint>
    </structure:Constraints>
  </message:Structures>
</message:Structure>

XMLParseError: RuntimeError

In [25]:
import sys
ausbs = sdmx.Request('ABS_XML')
data_msg = ausbs.data('RES_DWELL_ST')
data=data_msg.data[0]

In [26]:
set(series_key.REGION for series_key in data.series.keys())

{<KeyValue: REGION=1>,
 <KeyValue: REGION=2>,
 <KeyValue: REGION=3>,
 <KeyValue: REGION=4>,
 <KeyValue: REGION=5>,
 <KeyValue: REGION=6>,
 <KeyValue: REGION=7>,
 <KeyValue: REGION=8>,
 <KeyValue: REGION=AUS>}

In [27]:
key= ['1', '2', '3', '4', '5', '6', '7', '8', 'AUS']

In [27]:
AUS = [s for sk, s in data.series.items() if sk.REGION == 'AUS']

In [30]:
cur_df = pd.concat(sdmx.to_pandas(AUS)).unstack()
cur_df.tail()

,,TIME_PERIOD,2011-Q3,2011-Q4,2012-Q1,2012-Q2,2012-Q3,2012-Q4,2013-Q1,2013-Q2,2013-Q3,2013-Q4,...,2019-Q4,2020-Q1,2020-Q2,2020-Q3,2020-Q4,2021-Q1,2021-Q2,2021-Q3,2021-Q4,2022-Q1
MEASURE,REGION,FREQ,,,,,,,,,,,,,,,,,,,,,
1,AUS,Q,4418854.0,4400528.1,4428147.6,4456988.8,4439837.5,4550517.2,4607351.1,4688260.2,4774137.0,4953517.2,...,7170832.2,7278072.7,7251093.3,7487531.1,7886460.5,8360913.5,8807771.4,9433076.1,9952366.5,10173551.0
2,AUS,Q,4185069.8,4167616.1,4193208.0,4221012.0,4206315.6,4312946.9,4368207.4,4447442.1,4530851.3,4703735.9,...,6847451.4,6949644.6,6922424.0,7149079.1,7529498.4,7989261.9,8418679.4,9013780.7,9513275.8,9723708.3
3,AUS,Q,233784.2,232911.9,234939.6,235976.8,233521.9,237570.3,239143.7,240818.2,243285.8,249781.4,...,323380.9,328428.1,328669.3,338452.0,356962.2,371651.6,389092.0,419295.4,439090.7,449842.7
4,AUS,Q,9002.7,9037.2,9063.4,9097.6,9130.2,9166.1,9193.9,9226.9,9261.4,9299.4,...,10441.4,10476.6,10518.3,10557.8,10599.6,10633.7,10675.2,10715.0,10756.4,10801.4
5,AUS,Q,490.8,486.9,488.6,489.9,486.3,496.4,501.1,508.1,515.5,532.7,...,686.8,694.7,689.4,709.2,744.0,786.3,825.1,880.4,925.3,941.9

In [35]:
a = cur_df.transpose()
a.

MEASURE             1             2              3             4           5
REGION            AUS           AUS            AUS           AUS         AUS
FREQ                Q             Q              Q             Q           Q
count    4.300000e+01  4.300000e+01      43.000000     43.000000   43.000000
mean     6.345650e+06  6.048558e+06  297092.218605   9874.276744  636.641860
std      1.503147e+06  1.448515e+06   54944.828322    566.642463  115.468887
min      4.400528e+06  4.167616e+06  232911.900000   9002.700000  486.300000
25%      5.079993e+06  4.826771e+06  253222.050000   9347.950000  543.400000
50%      6.441224e+06  6.147746e+06  293478.400000   9884.800000  646.000000
75%      6.954308e+06  6.639713e+06  315345.600000  10372.050000  687.400000
max      1.017355e+07  9.723708e+06  449842.700000  10801.400000  941.900000

In [31]:
a = cur_df.pivot(columns='REGION')['TIME_PERIOD']

KeyError: "None of ['REGION'] are in the columns"